//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mauricio_991296005_ADN_W15_DLABS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string courseName { get; set; }
        public string courseCode { get; set; }
        public string enrolledStudents { get; set; }
        public string NumCredits { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
